name = "Lydia"
description = "A base template for use in my static projects"

homepage = "https://github.com/lydiascarf"
min_version = "0.15.0"
demo = ""
created=2023-07-31
updated=2023-07-31

[author]
name = "Lydia Scarf"
homepage = "https://github.com/lydiascarf"
